config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :schools, only: [:show, :index]
  root to: 'page#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :attachment,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/

  belongs_to :owner, polymorphic: true
end

app/models/school.rb
class School < ApplicationRecord
  TYPES = ["public", "private", "international"]

  has_attached_file :logo,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  has_many :photos, as: :owner, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  def logo_attributes=(attributes)
    # Marks the attachment for destruction on next save,
    # if the attributes hash contains a _destroy flag
    # and a new logo was not uploaded at the same time:
    logo.clear if has_destroy_flag?(attributes) && !logo.dirty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show]

  def index
    @schools = School.all
  end

  def show
  end

  private
    def set_school
      @school = School.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chọn Trường VN</title>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <%= yield %>

    <%= render 'shared/subscriber' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/page/home.html.erb
<%= render 'shared/paralax' %>
<%= render 'shared/features' %>

app/views/schools/index.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>

  <h1>Schools</h1>

  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @schools.each do |school| %>
        <tr>
          <td><%= school.name %></td>
          <td><%= link_to 'Show', school %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', schools_path %>

app/views/shared/_features.html.erb
<% school = School.first %>
<div class="container">
  <h2>Trường nổi bật</h2>
  <div class="owl-carousel owl-theme">
      <div class="item">
        <div>
          <%= image_tag(school.logo.url(:thumb), style: 'width: 40%;') %>
        </div>
      </div>
      <div class="item"><h4>2</h4></div>
      <div class="item"><h4>3</h4></div>
      <div class="item"><h4>4</h4></div>
      <div class="item"><h4>5</h4></div>
      <div class="item"><h4>6</h4></div>
      <div class="item"><h4>7</h4></div>
      <div class="item"><h4>8</h4></div>
      <div class="item"><h4>9</h4></div>
      <div class="item"><h4>11</h4></div>
      <div class="item"><h4>12</h4></div>
  </div>
</div>

<script>
$('.owl-carousel').owlCarousel({
  loop:true,
  margin:10,
  nav:true,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:3
      },
      1000:{
          items:5
      }
  }
})
</script>

<style>
.owl-carousel .item {
    height: 150px;
    padding: 1rem;
}
</style>

app/views/shared/_footer.html.erb
<footer class="footer footer-big">
            <!-- .footer-black is another class for the footer, for the transparent version, we recommend you to change the url of the image with your favourite image.          -->

            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                      CHON TRUONG VN
                    </div>
                    <div class="col-md-3 col-md-offset-1">
                        <h5 class="title">Company</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                       Find offers
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Discover
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Portfolio
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                       Our news
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                       About Us
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-md-3">
                        <h5 class="title"> Help and Support</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">
                                       Contact Us
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                       How it works
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Terms &amp; Conditions
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Company Policy
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                       Money Back
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-md-3">
                        <h5 class="title">Follow us on</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#" class="btn btn-social btn-facebook btn-simple">
                                        <i class="fa fa-facebook-square"></i> Facebook
                                    </a>
                                </li>
                                 <li>
                                     <a href="#" class="btn btn-social btn-dribbble btn-simple">
                                        <i class="fa fa-dribbble"></i> Dribbble
                                    </a>
                                </li>
                                <li>
                                   <a href="#" class="btn btn-social btn-twitter btn-simple">
                                        <i class="fa fa-twitter"></i> Twitter
                                    </a>
                                </li>
                                <li>
                                     <a href="#" class="btn btn-social btn-reddit btn-simple">
                                        <i class="fa fa-google-plus-square"></i> Google+
                                    </a>
                                </li>

                            </ul>
                        </nav>
                    </div>
                </div>
                <hr>
                <div class="copyright">
                    © 2016 Creative Tim, made with love
                </div>
            </div>
        </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-ct-blue">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-default2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        CHỌN TRƯỜNG <span style="text-decoration: underline; font-weight: bold;">VN</span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="navigation-default2">
      <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/"><i class="fa fa-home"></i> Trang chủ</a>
        </li>

        <li>
            <a href="/schools"><i class="fa fa-book"></i> Tất cả các trường</a>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_paralax.html.erb
<div class="hero-wrapper hero-college-hub">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<h1 class="text-center">Find Your <b>Dream School.</b></h1>

				<div class="tab-content">
					<div class="tab-pane active" id="college" style="border-top-left-radius: 0px;">
						<form action="/college-search" method="get" novalidate="novalidate">
							<div class="row gutter-minimal">
								<div class="col-sm-8">
                  <input type="text" class="form-control">
								</div>
								<div class="col-sm-4">
									<button type="submit" class="btn btn-primary btn-block">Search</button>
								</div>
							</div>
						</form>
					</div>
				</div>
				<p class="sub-search">or <a href="/college-search" class="browse-by">browse by location or major <i class="fa fa-angle-right"></i></a></p>
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center">
						<p class="text-center" style="margin-top:30px;">Want one-on-one help from a former admissions officer?<br>Our College Counselors can help you find, apply, and get accepted to the best schools.</p>
						<a href="/college-admissions/get-accepted" class="btn btn-secondary btn-block-xs">Learn More</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_social_line.html.erb
<div class="social-line">
             <div class="container">
                <div class="row">
                     <div class="col-md-3">
                        <h4 class="title">Thank you for sharing!</h4>
                    </div>
                     <div class="col-md-2">
                         <a href="" class="btn btn-round btn-fill btn-social btn-facebook">
                             <i class="fa fa-facebook-square"></i> Share · 753
                         </a>
                     </div>
                      <div class="col-md-2">
                         <a href="" class="btn btn-round btn-fill btn-social btn-twitter">
                             <i class="fa fa-twitter"></i> Tweet · 832
                         </a>
                     </div>
                      <div class="col-md-2">
                         <a href="" class="btn btn-round btn-fill btn-social btn-google">
                             <i class="fa fa-google-plus-square"></i> Share · 131
                         </a>
                     </div>
                     <div class="col-md-2">
                         <a href="" class="btn btn-round btn-social  btn-fill btn-youtube">
                             <i class="fa fa-pinterest"></i> Pin it · 323
                         </a>
                     </div>
                </div>
             </div>
         </div>

app/views/shared/_subscriber.html.erb
<div class="subscribe-line subscribe-line-transparent">
             <div class="container">
                <div class="row">
                     <div class="col-md-9">
                        <form class="">
                             <div class="form-group">
                                  <input type="text" value="" class="form-control" placeholder="Enter your email...">
                             </div>
                         </form>
                     </div>
                     <div class="col-md-3">
                         <button type="button" class="btn btn-info btn-fill btn-block">Subscribe Now!</button>
                     </div>
                </div>
             </div>
         </div>